apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jenkins-custom
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./Charts/grafana_HR
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    grafana:
      resources:
        limits:
          cpu: 300m
          memory: 512Mi
